In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

# Loading necessary files from my Google Drive
stops = pd.read_csv('/content/drive/My Drive/google_transit/stops.txt')
trips = pd.read_csv('/content/drive/My Drive/google_transit/trips.txt')
stop_times = pd.read_csv('/content/drive/My Drive/google_transit/stop_times.txt')
routes = pd.read_csv('/content/drive/My Drive/google_transit/routes.txt')

# Just checking the first few rows of each file to ensure everything is loaded correctly
print(stops.head())
print(trips.head())
print(stop_times.head())
print(routes.head())

  stop_id                  stop_name   stop_lat   stop_lon  location_type  \
0     101  Van Cortlandt Park-242 St  40.889248 -73.898583            1.0
1    101N  Van Cortlandt Park-242 St  40.889248 -73.898583            NaN
2    101S  Van Cortlandt Park-242 St  40.889248 -73.898583            NaN
3     103                     238 St  40.884667 -73.900870            1.0
4    103N                     238 St  40.884667 -73.900870            NaN

  parent_station
0            NaN
1            101
2            101
3            NaN
4            103
  route_id                                 trip_id service_id  \
0        1  ASP24GEN-1038-Sunday-00_000600_1..S03R     Sunday
1        1  ASP24GEN-1038-Sunday-00_002600_1..S03R     Sunday
2        1  ASP24GEN-1038-Sunday-00_004600_1..S03R     Sunday
3        1  ASP24GEN-1038-Sunday-00_006600_1..S03R     Sunday
4        1  ASP24GEN-1038-Sunday-00_007200_1..N03R     Sunday

               trip_headsign  direction_id shape_id
0                South Ferry             1  1..S03R
1                South Ferry             1  1..S03R
2                South Ferry             1  1..S03R
3                South Ferry             1  1..S03R
4  Van Cortlandt Park-242 St             0  1..N03R
                                  trip_id stop_id arrival_time departure_time  \
0  ASP24GEN-1038-Sunday-00_000600_1..S03R    101S     00:06:00       00:06:00
1  ASP24GEN-1038-Sunday-00_000600_1..S03R    103S     00:07:30       00:07:30
2  ASP24GEN-1038-Sunday-00_000600_1..S03R    104S     00:09:00       00:09:00
3  ASP24GEN-1038-Sunday-00_000600_1..S03R    106S     00:10:30       00:10:30
4  ASP24GEN-1038-Sunday-00_000600_1..S03R    107S     00:12:00       00:12:00

   stop_sequence
0              1
1              2
2              3
3              4
4              5
  agency_id route_id route_short_name            route_long_name  route_type  \
0  MTA NYCT        1                1  Broadway - 7 Avenue Local           1
1  MTA NYCT        2                2           7 Avenue Express           1
2  MTA NYCT        3                3           7 Avenue Express           1
3  MTA NYCT        4                4   Lexington Avenue Express           1
4  MTA NYCT        5                5   Lexington Avenue Express           1

                                          route_desc  \
0  Trains operate between 242 St in the Bronx and...
1  Trains operate between Wakefield-241 St, Bronx...
2  Trains operate between 148 St, 7 Av, Manhattan...
3  Trains operate daily between Woodlawn/Jerome A...
4  Weekdays daytime, most trains operate between ...

                                        route_url route_color route_text_color
0  http://web.mta.info/nyct/service/pdf/t1cur.pdf      EE352E              NaN
1  http://web.mta.info/nyct/service/pdf/t2cur.pdf      EE352E              NaN
2  http://web.mta.info/nyct/service/pdf/t3cur.pdf      EE352E              NaN
3  http://web.mta.info/nyct/service/pdf/t4cur.pdf      00933C              NaN
4  http://web.mta.info/nyct/service/pdf/t5cur.pdf      00933C              NaN

In [3]:
# Merging stop_times with stops so that I can get detailed station info for each trip
trips_with_stops = pd.merge(stop_times, stops, on='stop_id')

# Now, I’ll merge the trip details with stops
full_trip_info = pd.merge(trips_with_stops, trips, on='trip_id')

# Finally, merging with routes to get complete details for each trip
full_trip_info = pd.merge(full_trip_info, routes, on='route_id')

# Checking the result to make sure the merges worked
print(full_trip_info.head())

                                  trip_id stop_id arrival_time departure_time  \
0  ASP24GEN-1038-Sunday-00_000600_1..S03R    101S     00:06:00       00:06:00
1  ASP24GEN-1038-Sunday-00_000600_1..S03R    103S     00:07:30       00:07:30
2  ASP24GEN-1038-Sunday-00_000600_1..S03R    104S     00:09:00       00:09:00
3  ASP24GEN-1038-Sunday-00_000600_1..S03R    106S     00:10:30       00:10:30
4  ASP24GEN-1038-Sunday-00_000600_1..S03R    107S     00:12:00       00:12:00

   stop_sequence                  stop_name   stop_lat   stop_lon  \
0              1  Van Cortlandt Park-242 St  40.889248 -73.898583
1              2                     238 St  40.884667 -73.900870
2              3                     231 St  40.878856 -73.904834
3              4         Marble Hill-225 St  40.874561 -73.909831
4              5                     215 St  40.869444 -73.915279

   location_type parent_station  ... direction_id shape_id agency_id  \
0            NaN            101  ...            1  1..S03R  MTA NYCT
1            NaN            103  ...            1  1..S03R  MTA NYCT
2            NaN            104  ...            1  1..S03R  MTA NYCT
3            NaN            106  ...            1  1..S03R  MTA NYCT
4            NaN            107  ...            1  1..S03R  MTA NYCT

   route_short_name            route_long_name route_type  \
0                 1  Broadway - 7 Avenue Local          1
1                 1  Broadway - 7 Avenue Local          1
2                 1  Broadway - 7 Avenue Local          1
3                 1  Broadway - 7 Avenue Local          1
4                 1  Broadway - 7 Avenue Local          1

                                          route_desc  \
0  Trains operate between 242 St in the Bronx and...
1  Trains operate between 242 St in the Bronx and...
2  Trains operate between 242 St in the Bronx and...
3  Trains operate between 242 St in the Bronx and...
4  Trains operate between 242 St in the Bronx and...

                                        route_url  route_color  \
0  http://web.mta.info/nyct/service/pdf/t1cur.pdf       EE352E
1  http://web.mta.info/nyct/service/pdf/t1cur.pdf       EE352E
2  http://web.mta.info/nyct/service/pdf/t1cur.pdf       EE352E
3  http://web.mta.info/nyct/service/pdf/t1cur.pdf       EE352E
4  http://web.mta.info/nyct/service/pdf/t1cur.pdf       EE352E

  route_text_color
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN

[5 rows x 23 columns]

In [4]:
# Loading additional files from google_transit_supplemented in case I need extra information
supplemented_stops = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/stops.txt')  # Adjust the path
supplemented_trips = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/trips.txt')
supplemented_stop_times = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/stop_times.txt')
supplemented_routes = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/routes.txt')

# Just making sure the supplemented files were loaded properly
print(supplemented_stops.head())
print(supplemented_trips.head())
print(supplemented_stop_times.head())
print(supplemented_routes.head())

  stop_id                  stop_name   stop_lat   stop_lon  location_type  \
0     101  Van Cortlandt Park-242 St  40.889248 -73.898583            1.0
1    101N  Van Cortlandt Park-242 St  40.889248 -73.898583            NaN
2    101S  Van Cortlandt Park-242 St  40.889248 -73.898583            NaN
3     103                     238 St  40.884667 -73.900870            1.0
4    103N                     238 St  40.884667 -73.900870            NaN

  parent_station
0            NaN
1            101
2            101
3            NaN
4            103
  route_id                                 trip_id  \
0        1  ASP24GEN-1038-Sunday-00_000600_1..S03R
1        1  ASP24GEN-1038-Sunday-00_002600_1..S03R
2        1  ASP24GEN-1038-Sunday-00_004600_1..S03R
3        1  ASP24GEN-1038-Sunday-00_006600_1..S03R
4        1  ASP24GEN-1038-Sunday-00_007200_1..N03R

                    service_id              trip_headsign  direction_id  \
0  ASP24GEN-1038-Sunday-00_C28                South Ferry             1
1  ASP24GEN-1038-Sunday-00_C28                South Ferry             1
2  ASP24GEN-1038-Sunday-00_C28                South Ferry             1
3  ASP24GEN-1038-Sunday-00_C28                South Ferry             1
4  ASP24GEN-1038-Sunday-00_C28  Van Cortlandt Park-242 St             0

  shape_id
0  1..S03R
1  1..S03R
2  1..S03R
3  1..S03R
4  1..N03R
                                  trip_id stop_id arrival_time departure_time  \
0  ASP24GEN-1038-Sunday-00_000600_1..S03R    101S     00:06:00       00:06:00
1  ASP24GEN-1038-Sunday-00_000600_1..S03R    103S     00:07:30       00:07:30
2  ASP24GEN-1038-Sunday-00_000600_1..S03R    104S     00:09:00       00:09:00
3  ASP24GEN-1038-Sunday-00_000600_1..S03R    106S     00:10:30       00:10:30
4  ASP24GEN-1038-Sunday-00_000600_1..S03R    107S     00:12:00       00:12:00

   stop_sequence
0              1
1              2
2              3
3              4
4              5
  agency_id route_id route_short_name            route_long_name  route_type  \
0  MTA NYCT        1                1  Broadway - 7 Avenue Local           1
1  MTA NYCT        2                2           7 Avenue Express           1
2  MTA NYCT        3                3           7 Avenue Express           1
3  MTA NYCT        4                4   Lexington Avenue Express           1
4  MTA NYCT        5                5   Lexington Avenue Express           1

                                          route_desc  \
0  Trains operate between 242 St in the Bronx and...
1  Trains operate between Wakefield-241 St, Bronx...
2  Trains operate between 148 St, 7 Av, Manhattan...
3  Trains operate daily between Woodlawn/Jerome A...
4  Weekdays daytime, most trains operate between ...

                                        route_url route_color route_text_color
0  http://web.mta.info/nyct/service/pdf/t1cur.pdf      EE352E              NaN
1  http://web.mta.info/nyct/service/pdf/t2cur.pdf      EE352E              NaN
2  http://web.mta.info/nyct/service/pdf/t3cur.pdf      EE352E              NaN
3  http://web.mta.info/nyct/service/pdf/t4cur.pdf      00933C              NaN
4  http://web.mta.info/nyct/service/pdf/t5cur.pdf      00933C              NaN

In [5]:
# Merging the supplemented data only if it provides additional info I need
full_trip_info = pd.merge(full_trip_info, supplemented_stops, on='stop_id', how='left')  # Example for stops
full_trip_info = pd.merge(full_trip_info, supplemented_trips, on='trip_id', how='left')  # Example for trips

# Checking the final merged dataset
print(full_trip_info.head())

                                  trip_id stop_id arrival_time departure_time  \
0  ASP24GEN-1038-Sunday-00_000600_1..S03R    101S     00:06:00       00:06:00
1  ASP24GEN-1038-Sunday-00_000600_1..S03R    103S     00:07:30       00:07:30
2  ASP24GEN-1038-Sunday-00_000600_1..S03R    104S     00:09:00       00:09:00
3  ASP24GEN-1038-Sunday-00_000600_1..S03R    106S     00:10:30       00:10:30
4  ASP24GEN-1038-Sunday-00_000600_1..S03R    107S     00:12:00       00:12:00

   stop_sequence                stop_name_x  stop_lat_x  stop_lon_x  \
0              1  Van Cortlandt Park-242 St   40.889248  -73.898583
1              2                     238 St   40.884667  -73.900870
2              3                     231 St   40.878856  -73.904834
3              4         Marble Hill-225 St   40.874561  -73.909831
4              5                     215 St   40.869444  -73.915279

   location_type_x parent_station_x  ...                stop_name_y  \
0              NaN              101  ...  Van Cortlandt Park-242 St
1              NaN              103  ...                     238 St
2              NaN              104  ...                     231 St
3              NaN              106  ...         Marble Hill-225 St
4              NaN              107  ...                     215 St

  stop_lat_y stop_lon_y  location_type_y parent_station_y route_id_y  \
0  40.889248 -73.898583              NaN              101          1
1  40.884667 -73.900870              NaN              103          1
2  40.878856 -73.904834              NaN              104          1
3  40.874561 -73.909831              NaN              106          1
4  40.869444 -73.915279              NaN              107          1

                  service_id_y trip_headsign_y  direction_id_y shape_id_y
0  ASP24GEN-1038-Sunday-00_C28     South Ferry             1.0    1..S03R
1  ASP24GEN-1038-Sunday-00_C28     South Ferry             1.0    1..S03R
2  ASP24GEN-1038-Sunday-00_C28     South Ferry             1.0    1..S03R
3  ASP24GEN-1038-Sunday-00_C28     South Ferry             1.0    1..S03R
4  ASP24GEN-1038-Sunday-00_C28     South Ferry             1.0    1..S03R

[5 rows x 33 columns]

In [6]:
import pandas as pd

# Loading the MTA turnstile data for the year 2022 from my Google Drive
turnstile_data = pd.read_csv('/content/drive/MyDrive/MTA_Subway_Turnstile_Data_2022.csv')

# Displaying the first few rows just to verify everything loaded correctly
print(turnstile_data.head())

    C/A  Unit       SCP Line Name Division        Date      Time Description  \
0  A002  R051  02-00-00   NQR456W      BMT  12/30/2022  03:00:00     REGULAR
1  A002  R051  02-00-00   NQR456W      BMT  12/30/2022  07:00:00     REGULAR
2  A002  R051  02-00-00   NQR456W      BMT  12/30/2022  11:00:00     REGULAR
3  A002  R051  02-00-00   NQR456W      BMT  12/30/2022  15:00:00     REGULAR
4  A002  R051  02-00-00   NQR456W      BMT  12/30/2022  19:00:00     REGULAR

   Entries  Exits
0  7811029                                            2770909
1  7811032                                            2770930
2  7811067                                            2771080
3  7811217                                            2771126
4  7811477                                            2771174

Cleaning/Processing the turnstile data

In [7]:
# Cleaning up column names to remove any leading or trailing spaces
turnstile_data.columns = turnstile_data.columns.str.strip()


# Renaming 'Entries' and 'Exits' columns to standardize the names for easier handling
turnstile_data.rename(columns={'Exits': 'EXITS', 'Entries': 'ENTRIES'}, inplace=True)

# Extracting only the columns that I’ll need for the analysis
turnstile_data = turnstile_data[['C/A', 'Unit', 'SCP', 'Line Name', 'Division', 'Date', 'Time', 'ENTRIES', 'EXITS']]

# Converting the 'Date' column to datetime format to make time-based analysis easier
turnstile_data['Date'] = pd.to_datetime(turnstile_data['Date'], format='%m/%d/%Y')

# Sorting the data by station and time to calculate daily entries and exits
turnstile_data = turnstile_data.sort_values(by=['C/A', 'Unit', 'SCP', 'Date', 'Time'])

# Calculating the daily entries and exits by taking the difference between consecutive rows for each turnstile
turnstile_data['Daily Entries'] = turnstile_data.groupby(['C/A', 'Unit', 'SCP'])['ENTRIES'].diff().fillna(0)
turnstile_data['Daily Exits'] = turnstile_data.groupby(['C/A', 'Unit', 'SCP'])['EXITS'].diff().fillna(0)

# Removing any rows where the difference is negative (this happens when the turnstile counter resets)
turnstile_data = turnstile_data[(turnstile_data['Daily Entries'] >= 0) & (turnstile_data['Daily Exits'] >= 0)]

# Showing the first few rows to check the calculations
print(turnstile_data[['C/A', 'Unit', 'SCP', 'Date', 'Time', 'Daily Entries', 'Daily Exits']].head())

           C/A  Unit       SCP       Date      Time  Daily Entries  \
10933172  A002  R051  02-00-00 2022-01-01  03:00:00            0.0
10933173  A002  R051  02-00-00 2022-01-01  07:00:00            4.0
10933174  A002  R051  02-00-00 2022-01-01  11:00:00           11.0
10933175  A002  R051  02-00-00 2022-01-01  15:00:00            8.0
10933176  A002  R051  02-00-00 2022-01-01  19:00:00           25.0

          Daily Exits
10933172          0.0
10933173          3.0
10933174         43.0
10933175         32.0
10933176         31.0

Realtime Service Status of each line

In [8]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd

# MTA Service Status API URL
url = "http://web.mta.info/status/serviceStatus.txt"

# Send a request to the API
response = requests.get(url)

# Check the response status
if response.status_code == 200:
    # Parse the XML response
    root = ET.fromstring(response.content)

    # Extract service status information for each subway line
    service_data = []
    for line in root.findall('.//line'):
        name = line.find('name').text
        status = line.find('status').text
        text = line.find('text').text if line.find('text') is not None else "No additional information"

        # Append service status data
        service_data.append({'line': name, 'status': status, 'info': text})

    # Convert to DataFrame for analysis
    service_status_df = pd.DataFrame(service_data)

    # Display the first few rows of service status data
    print(service_status_df.head())

    # Manually mapping Line Names from my turnstile data to the corresponding lines in service status
    line_map = {
        'NQR456W': '456',   # Mapping 'NQR456W' to '456'
        'NQR': 'NQR',       # Mapping 'NQR' lines
        'ACE': 'ACE',       # ACE lines
        'BDFM': 'BDFM',     # BDFM lines
        '123': '123',       # 123 lines
        '7': '7',           #7 line
        # Add more mappings here based on your turnstile data Line Name
    }

    # Assuming turnstile_data has already been loaded
    # turnstile_data = pd.read_csv('/path/to/turnstile_data.csv')

    # Applying the line mapping to my turnstile data
    turnstile_data['mapped_line'] = turnstile_data['Line Name'].map(line_map)

    # Merging the turnstile data with service status data based on the mapped lines
    subway_service_merged_data = pd.merge(turnstile_data, service_status_df, left_on='mapped_line', right_on='line', how='left')


    # Displaying the merged dataset to ensure everything looks good
    print(subway_service_merged_data.head())

else:
    print(f"Failed to retrieve data. HTTP Status code: {response.status_code}")

   line                      status  \
0   123  PLANNED - STATIONS SKIPPED
1   456  PLANNED - MULTIPLE IMPACTS
2     7    PLANNED - PART SUSPENDED
3   ACE  PLANNED - LOCAL TO EXPRESS
4  BDFM        NO SCHEDULED SERVICE

                                                info
0  \n                <span class="TitlePlannedWor...
1  \n                <span class="TitlePlannedWor...
2  \n                <span class="TitlePlannedWor...
3  \n                <span class="TitlePlannedWor...
4  \n                <span class="TitlePlannedWor...
    C/A  Unit       SCP Line Name Division       Date      Time  ENTRIES  \
0  A002  R051  02-00-00   NQR456W      BMT 2022-01-01  03:00:00  7675872
1  A002  R051  02-00-00   NQR456W      BMT 2022-01-01  07:00:00  7675876
2  A002  R051  02-00-00   NQR456W      BMT 2022-01-01  11:00:00  7675887
3  A002  R051  02-00-00   NQR456W      BMT 2022-01-01  15:00:00  7675895
4  A002  R051  02-00-00   NQR456W      BMT 2022-01-01  19:00:00  7675920

     EXITS  Daily Entries  Daily Exits mapped_line line  \
0  2649548            0.0          0.0         456  456
1  2649551            4.0          3.0         456  456
2  2649594           11.0         43.0         456  456
3  2649626            8.0         32.0         456  456
4  2649657           25.0         31.0         456  456

                       status  \
0  PLANNED - MULTIPLE IMPACTS
1  PLANNED - MULTIPLE IMPACTS
2  PLANNED - MULTIPLE IMPACTS
3  PLANNED - MULTIPLE IMPACTS
4  PLANNED - MULTIPLE IMPACTS

                                                info
0  \n                <span class="TitlePlannedWor...
1  \n                <span class="TitlePlannedWor...
2  \n                <span class="TitlePlannedWor...
3  \n                <span class="TitlePlannedWor...
4  \n                <span class="TitlePlannedWor...

Was trying to push the code on GitHub

In [9]:
# Remove existing remote origin (to avoid the 'remote origin already exists' error)
!git remote remove origin

# Adding the correct remote origin (your repository URL)
!git remote add origin https://github.com/VedAralkar/NYC_Subway_Analysis.git

# Check if the notebook file exists and use the correct path
!ls drive/MyDrive/

# Add the notebook file (ensure the path is correct after checking the above step)
!git add "drive/MyDrive/Capstone Project Pace.ipynb"

!git commit -m "Initial commit - adding Capstone Project notebook"

# Renaming the branch from 'master' to 'main' (if not already done)
!git branch -M main

# Pushing the changes to the 'main' branch on GitHub
!git push -u origin main

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
 1052190799.xlsx
 20170427_195606.jpg
 20180529_220143.jpg
'2018-06-28 08.06.00 1 (1).jpg'
'2018-06-28 08.06.00 1.jpg'
'20180708_163636 (1).jpg'
 20180708_163636.jpg
 20190418_141342.png
'2023-12-14_01-51-29 final exam.gdoc'
'2. Entry Level Data Scientist Resume.docx'
'404 - Ved Aralkar.pdf'
 681372231687-7591152969-ticket.pdf
 a1.txt
'A2 FORM .gdoc'
'A2 FORM .pdf'
'Abhilasha ❤️'
 AirQualityUCI.csv
 API_SP.URB.TOTL_DS2_en_excel_v2_2924431.xls
'Arduino Project PPT.gslides'
'Ascot Group Cover Letter.gdoc'
'Assignment_1 Ved Aralkar .gdoc'
 Assignment2_DataMining.gdoc
'Assignment_2 Ved Aralkar.gdoc'
 Assignment.ipynb
 Automated_Traffic_Volume.csv
 Automated_Traffic_Volume_Small.gsheet
 Azzuro.jpg
 Bae.jpg
 Blur.jpg
'C1 poster '
'C1 Roll No-04.pdf'
'C2 Assignment__Ved Aralkar__04.pdf'
'Case Diagram.pdf'
'CGI Cover Letter.gdoc'
'Chapter 2.gsheet'
'Chapter 3.gsheet'
'Class Diagram.pdf'
 Classroom
'Codes and Graphs.gdoc'
'Colab Notebooks'
'Copy of Numpy.ipynb'
'CS673_Assignment3_Ved Aralkar.gdoc'
'CS675: HW4_Ved Aralkar.gdoc'
'CS675 HW4_Ved Aralkar.gslides'
 CS675_va17957n_Assignment3.gdoc
'Dapoli 2019'
'Data Mining_Final Exam_Ved Aralkar.gdoc'
'Data_MiningMidterm Exam_Ved Aralkar.gdoc'
'Data Science London Uni.doc'
'Data Science London Uni.gdoc'
'DBMS Final Presentation.gdoc'
"DD's 18th.jpg"
'Declaration of 2021-22 (1).pdf'
'Div_A_Roll No. 04_Ved Aralkar.gdoc'
'Documents '
'Electronics Assignment__Ved Aralkar__04.pdf'
'EVS Assignment 1 __Ved Aralkar__ 04.pdf'
'EVS Assignment 3__Ved Aralkar__04.pdf'
 farthest.docx
 farthest.gdoc
'FOR PARENTS USA VISA- Invitation from Ved Aralkar DEC 2024.docx'
 google_transit
 google_transit_supplemented
'Homework1 Intro to DS.gdoc'
'How to get started with Drive.pdf'
'Hw1 .gsheet'
'HW - Excel Review.xlsx'
 IMG-20170113-WA0039.jpg
 IMG-20170311-WA0001.jpg
 IMG-20170330-WA0018.jpg
 IMG-20170330-WA0027.jpg
 IMG-20170330-WA0041.jpg
 IMG-20170330-WA0042.jpg
 IMG-20170403-WA0004.jpg
 IMG-20170412-WA0014.jpg
 IMG-20170530-WA0018.jpg
 IMG-20170617-WA0003.jpg
 IMG-20170815-WA0033.jpg
 IMG-20180322-WA0033.jpg
'IMG-20180408-WA0006 (1).jpg'
 IMG-20180408-WA0006.jpg
 IMG-20180831-WA0010.jpg
 IMG-20180901-WA0006.jpg
 IMG-20190407-WA0011.jpg
 IMG-20190504-WA0001.jpg
 IMG_20220524_140404-2.jpg
 IMG_8046.HEIC
'Installment 3.png'
'Introduction to Data Science: Assignment 5.gdoc'
'Introduction to Data Science: Final Exam_va17957n.gdoc'
'Introduction To Data Structure - Tri-V.pptx'
'Item-prod (1).xlsx'
 Item-prod-28032020.gsheet
'Item-prod (2).xlsx'
 Item-prod.gsheet
 Item-prod.xlsx
'Machine Learning Assignment 2 Ved .gdoc'
'Maths Assignment__Ved Aralkar__04.pdf'
'MCWOG Permanent License.gdoc'
'MCWOG Permanent License.pdf'
 Memories
 MTA_Subway_Turnstile_Data_2022.csv
'Nandish 20th.jpg'
 nearest.docx
 nearest.gdoc
 nyc_temp_2003_2021.csv
 NYPD_Data.csv
'Onkar Mistry.docx'
'Online Movie Ticket Booking.gdoc'
'Outlier (Scale AI) Cover Letter.gdoc'
'Parkinsons Disease Voice Analysis.gdoc'
'Parkinsson disease.gsheet'
'Parth Aralkar CV.pdf'
 passport_size_photo.pdf
'PEACE ASSIGNMENT 29.docx'
'PEACE ASSIGNMENT 29.gdoc'
'Peace PPT.gslides'
 pgd_sql_U1C1-2963.gdoc
 pgd_sql_U1C1-2963.pdf
'Photo from Ved Aralkar'
'PitchBook Cover Letter.gdoc'
'Project 2: Section B_U01883225.gdoc'
 received_601731486703970.jpeg
'Sai assignment 6 .gdoc'
'Sample resume.docx'
'Sample SOP for MS in CS (1).gdoc'
'Sample SOP for MS in CS.gdoc'
'Sample SOP for MS in CS.pdf'
 SB42720N_Assignment3.gdoc
'Scalable Database Assignment1_Ved Aralkar.gdoc'
'Scalable Databases: Assignment 4.gdoc'
'Scalable Databases Assignment 5.gdoc'
'Scalable Databases Final Project.gdoc'
 Screenshot_20161104-153303.png
 Screenshot_20171019-191900.png
 Screenshot_20180114-210627.png
'Screenshot_20180131-203822 (1).png'
 Screenshot_20180131-203822.png
 Screenshot_20180412-130918.png
 Screenshot_20180424-134839.png
 Screenshot_20180512-192255.png
 Screenshot_20180601-225506.png
 Screenshot_20180601-231929.png
 Screenshot_20180603-091507.png
 Screenshot_20190330-083008.png
 Screenshot_20190414-232225.png
 Screenshot_20190430-222746.png
 Screenshot_20210729-091645.jpg
 Screenshot_20220707-133257__01.jpg
 Screenshot_20220716-122927__01.jpg
 SI_20170602_231412.jpg
 Snapchat-1030054773.jpg
 Snapchat-1563247246.jpg
'Snapchat-1824399312 (1).jpg'
 Snapchat-1824399312.jpg
 Snapchat-1938524720.jpg
 spotify-2023.gsheet
 taxi+_zone_lookup.gsheet
'Trimester 1 GC.pdf'
 Trimester2.pdf
 Trimester3.pdf
 Trimester4.pdf
'Trimester5 (1).pdf'
 Trimester5.pdf
'Trimester6 (1).jpg'
 Trimester6.jpg
'Untitled document (1).gdoc'
'Untitled document (2).gdoc'
'Untitled document (3).gdoc'
'Untitled document (4).gdoc'
'Untitled document.gdoc'
'Untitled presentation.gslides'
'Untitled spreadsheet (1).gsheet'
'Untitled spreadsheet (2).gsheet'
'Untitled spreadsheet.gsheet'
 users.gsheet
 va17957n_Assginment3.gdoc
'Ved Aralkar__04__C1 Assignment.pdf'
'Ved Aralkar  (1).pdf'
'Ved Aralkar 20170516_203008.jpg'
'Ved Aralkar  (2).pdf'
'Ved Aralkar_Assignment 6 .gdoc'
'Ved Aralkar CoverLetter BNY Mellon.gdoc'
'Ved Aralkar cover letter Point72.gdoc'
'Ved Aralkar Cover Letter Red Ventures.gdoc'
'Ved Aralkar.docx'
'Ved Aralkar Payment Receipt.pdf'
'Ved Aralkar .pdf'
'Ved Aralkar_Resume'
'Ved Aralkar_Resume.docx'
'Ved Aralkar_Resume.gdoc'
'Ved Aralkar Sezzle Cover Letter.gdoc'
'Ved Resume Final.pdf'
 VID_20220524_151640.mp4
'Weather Dataset 2022.csv'
 weather.gsheet
 Worldbank_urban-population-per-country.gsheet
 yellow_tripdata_2023-05.parquet
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

Importing Weather Dataset

In [10]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
weather_data = pd.read_csv('/content/drive/MyDrive/Weather Dataset 2022.csv')
print(weather_data.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
         date  tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
0  2022-01-01   9.7   6.4  11.6  24.0   NaN   150   7.8   NaN  1008.1   NaN
1  2022-01-02   9.1   1.8  13.4   5.2   NaN   315  15.7   NaN  1005.6   NaN
2  2022-01-03  -1.9  -4.6   1.3   2.5   NaN     1  22.7   NaN  1019.4   NaN
3  2022-01-04  -2.8  -6.2   0.8   0.0   NaN   270  11.1   NaN  1028.1   NaN
4  2022-01-05   3.0  -1.5   7.9   3.3   NaN   224  13.3   NaN  1014.3   NaN

Version 2 code:

In [11]:
#Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Importing necessary libraries
import pandas as pd
import requests
import xml.etree.ElementTree as ET
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#Loading GTFS and Turnstile Data from Google Drive
stops = pd.read_csv('/content/drive/My Drive/google_transit/stops.txt')
trips = pd.read_csv('/content/drive/My Drive/google_transit/trips.txt')
stop_times = pd.read_csv('/content/drive/My Drive/google_transit/stop_times.txt')
routes = pd.read_csv('/content/drive/My Drive/google_transit/routes.txt')

turnstile_data = pd.read_csv('/content/drive/MyDrive/MTA_Subway_Turnstile_Data_2022.csv')
turnstile_data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,C/A,Unit,SCP,Line Name,Division,Date,Time,Description,Entries,Exits
0,A002,R051,02-00-00,NQR456W,BMT,12/30/2022,03:00:00,REGULAR,7811029,2770909
1,A002,R051,02-00-00,NQR456W,BMT,12/30/2022,07:00:00,REGULAR,7811032,2770930
2,A002,R051,02-00-00,NQR456W,BMT,12/30/2022,11:00:00,REGULAR,7811067,2771080
3,A002,R051,02-00-00,NQR456W,BMT,12/30/2022,15:00:00,REGULAR,7811217,2771126
4,A002,R051,02-00-00,NQR456W,BMT,12/30/2022,19:00:00,REGULAR,7811477,2771174

In [12]:
#Cleaning and preparing Turnstile Data
turnstile_data.columns = turnstile_data.columns.str.strip()  # Clean column names
turnstile_data.rename(columns={'Entries': 'ENTRIES', 'Exits': 'EXITS'}, inplace=True)  # Rename columns

#Calculating Daily Entries and Exits
turnstile_data['Daily Entries'] = turnstile_data.groupby(['C/A', 'Unit', 'SCP'])['ENTRIES'].diff().fillna(0)
turnstile_data['Daily Exits'] = turnstile_data.groupby(['C/A', 'Unit', 'SCP'])['EXITS'].diff().fillna(0)

#Removing negative values caused by counter resets
turnstile_data = turnstile_data[(turnstile_data['Daily Entries'] >= 0) & (turnstile_data['Daily Exits'] >= 0)]


#Loading Weather Data and Merge with Turnstile Data

#Ensuring weather data has correct datetime format for merging
weather_data['date'] = pd.to_datetime(weather_data['date'], format='%Y-%m-%d')
weather_data.head()

#Converting turnstile Date to datetime
turnstile_data['Date'] = pd.to_datetime(turnstile_data['Date'])

#Mapping the subway lines to 'mapped_line' before merging
line_map = {'NQR456W': '456', 'NQR': 'NQR', 'ACE': 'ACE', 'BDFM': 'BDFM', '123': '123', '7': '7'}
turnstile_data['mapped_line'] = turnstile_data['Line Name'].map(line_map)

#Merging Turnstile Data with Weather Data, ensuring 'mapped_line' is retained
subway_weather_data = pd.merge(turnstile_data, weather_data, left_on='Date', right_on='date', how='left')

#Extracting relevant weather features (e.g., temperature, precipitation)
subway_weather_data['Is_Cold'] = subway_weather_data['tavg'].apply(lambda x: 1 if x < 32 else 0)
subway_weather_data['Is_Rainy'] = subway_weather_data['prcp'].apply(lambda x: 1 if x > 0 else 0)

In [13]:
weather_data.head()

        date  tavg  tmin  tmax  prcp  snow  wdir  wspd  wpgt    pres  tsun
0 2022-01-01   9.7   6.4  11.6  24.0   NaN   150   7.8   NaN  1008.1   NaN
1 2022-01-02   9.1   1.8  13.4   5.2   NaN   315  15.7   NaN  1005.6   NaN
2 2022-01-03  -1.9  -4.6   1.3   2.5   NaN     1  22.7   NaN  1019.4   NaN
3 2022-01-04  -2.8  -6.2   0.8   0.0   NaN   270  11.1   NaN  1028.1   NaN
4 2022-01-05   3.0  -1.5   7.9   3.3   NaN   224  13.3   NaN  1014.3   NaN

In [14]:
subway_weather_data.head()

,C/A,Unit,SCP,Line Name,Division,Date,Time,Description,ENTRIES,EXITS,...,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,Is_Cold,Is_Rainy
0,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,03:00:00,REGULAR,7811029,2770909,...,11.8,0.0,NaN,282,7.2,NaN,1025.0,NaN,1,0
1,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,07:00:00,REGULAR,7811032,2770930,...,11.8,0.0,NaN,282,7.2,NaN,1025.0,NaN,1,0
2,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,11:00:00,REGULAR,7811067,2771080,...,11.8,0.0,NaN,282,7.2,NaN,1025.0,NaN,1,0
3,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,15:00:00,REGULAR,7811217,2771126,...,11.8,0.0,NaN,282,7.2,NaN,1025.0,NaN,1,0
4,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,19:00:00,REGULAR,7811477,2771174,...,11.8,0.0,NaN,282,7.2,NaN,1025.0,NaN,1,0

In [15]:
#Retrieving MTA Service Status via API (as before)
url = "http://web.mta.info/status/serviceStatus.txt"
response = requests.get(url)
if response.status_code == 200:
    root = ET.fromstring(response.content)
    service_data = []
    for line in root.findall('.//line'):
        name = line.find('name').text
        status = line.find('status').text
        text = line.find('text').text if line.find('text') is not None else "No additional information"
        service_data.append({'line': name, 'status': status, 'info': text})
    service_status_df = pd.DataFrame(service_data)

#Merging All Data (Turnstile + Weather + Service Status)
#Ensuring 'mapped_line' is carried over in both datasets
subway_final_data = pd.merge(subway_weather_data, service_status_df, left_on='mapped_line', right_on='line', how='left')

#Extracting Time Features for Modeling (as before)
subway_final_data['Hour'] = pd.to_datetime(subway_final_data['Time']).dt.hour
subway_final_data['Day_of_Week'] = subway_final_data['Date'].dt.dayofweek

#Ensuring 'Is_Cold' and 'Is_Rainy' exist in the final merged dataset
print(subway_final_data[['Date', 'mapped_line', 'Daily Entries', 'Daily Exits', 'Hour', 'Day_of_Week', 'Is_Cold', 'Is_Rainy', 'status']].head())

<ipython-input-15-7c9f03e9a5cf>:19: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  subway_final_data['Hour'] = pd.to_datetime(subway_final_data['Time']).dt.hour

        Date mapped_line  Daily Entries  Daily Exits  Hour  Day_of_Week  \
0 2022-12-30         456            0.0          0.0     3            4
1 2022-12-30         456            3.0         21.0     7            4
2 2022-12-30         456           35.0        150.0    11            4
3 2022-12-30         456          150.0         46.0    15            4
4 2022-12-30         456          260.0         48.0    19            4

   Is_Cold  Is_Rainy                      status
0        1         0  PLANNED - MULTIPLE IMPACTS
1        1         0  PLANNED - MULTIPLE IMPACTS
2        1         0  PLANNED - MULTIPLE IMPACTS
3        1         0  PLANNED - MULTIPLE IMPACTS
4        1         0  PLANNED - MULTIPLE IMPACTS

In [16]:
subway_final_data.head()

,C/A,Unit,SCP,Line Name,Division,Date,Time,Description,ENTRIES,EXITS,...,wpgt,pres,tsun,Is_Cold,Is_Rainy,line,status,info,Hour,Day_of_Week
0,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,03:00:00,REGULAR,7811029,2770909,...,NaN,1025.0,NaN,1,0,456,PLANNED - MULTIPLE IMPACTS,"\n <span class=""TitlePlannedWor...",3,4
1,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,07:00:00,REGULAR,7811032,2770930,...,NaN,1025.0,NaN,1,0,456,PLANNED - MULTIPLE IMPACTS,"\n <span class=""TitlePlannedWor...",7,4
2,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,11:00:00,REGULAR,7811067,2771080,...,NaN,1025.0,NaN,1,0,456,PLANNED - MULTIPLE IMPACTS,"\n <span class=""TitlePlannedWor...",11,4
3,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,15:00:00,REGULAR,7811217,2771126,...,NaN,1025.0,NaN,1,0,456,PLANNED - MULTIPLE IMPACTS,"\n <span class=""TitlePlannedWor...",15,4
4,A002,R051,02-00-00,NQR456W,BMT,2022-12-30,19:00:00,REGULAR,7811477,2771174,...,NaN,1025.0,NaN,1,0,456,PLANNED - MULTIPLE IMPACTS,"\n <span class=""TitlePlannedWor...",19,4

In [17]:
#Preparing Features (X) and Target (y) for Modeling

#Defining the features (inputs) for the model
X = subway_final_data[['Is_Cold', 'Is_Rainy', 'tavg', 'prcp', 'Hour', 'Day_of_Week']]  # Features

#Defining the target (what are we predicting)
y = subway_final_data['Daily Entries']  # Target: predicting the number of daily entries

#Displaying the first few rows of features and target to ensure correctness
print(X.head())
print(y.head())

   Is_Cold  Is_Rainy  tavg  prcp  Hour  Day_of_Week
0        1         0   5.6   0.0     3            4
1        1         0   5.6   0.0     7            4
2        1         0   5.6   0.0    11            4
3        1         0   5.6   0.0    15            4
4        1         0   5.6   0.0    19            4
0      0.0
1      3.0
2     35.0
3    150.0
4    260.0
Name: Daily Entries, dtype: float64

In [18]:
#Splitting Data into Training and Testing Sets
from sklearn.model_selection import train_test_split

#Splitting the data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Displaying the shape of the datasets to ensure correctness
print(f"Training features: {X_train.shape}, Training target: {y_train.shape}")
print(f"Testing features: {X_test.shape}, Testing target: {y_test.shape}")

Training features: (7268837, 6), Training target: (7268837,)
Testing features: (1817210, 6), Testing target: (1817210,)

In [19]:
#Training a Linear Regression Model
from sklearn.linear_model import LinearRegression

#Initializing the model
model = LinearRegression()

#Training (fit) the model on the training data
model.fit(X_train, y_train)

#Displaying the model coefficients
print(f"Model Coefficients: {model.coef_}")

Model Coefficients: [    0.         -1427.95891834    23.30656332   101.438723
 -1243.28135024  -738.9348084 ]

In [20]:
#Making Predictions and Evaluating the Model
from sklearn.metrics import mean_squared_error

#Using the trained model to make predictions on the test set
y_pred = model.predict(X_test)

#Calculating the Mean Squared Error (MSE) between the actual and predicted values
mse = mean_squared_error(y_test, y_pred)

#Displaying the MSE and the first few predictions
print(f"Mean Squared Error: {mse}")
print(f"First 5 Predictions: {y_pred[:5]}")
print(f"Actual values: {y_test.values[:5]}")

Mean Squared Error: 10169233015510.256
First 5 Predictions: [ 8986.08895448 -7755.16922822 14210.61001073 18446.70269126
 -2705.64510473]
Actual values: [327.  81. 116.  33.  33.]

In [ ]:
#Trying Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

#Initializing the model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

#Training the model
rf_model.fit(X_train, y_train)

#Making predictions on the test set
y_pred_rf = rf_model.predict(X_test)

#Calculating MSE for Random Forest
mse_rf = mean_squared_error(y_test, y_pred_rf)

#Displaying the MSE and first few predictions
print(f"Random Forest Mean Squared Error: {mse_rf}")
print(f"First 5 Random Forest Predictions: {y_pred_rf[:5]}")
print(f"Actual values: {y_test.values[:5]}")

In [ ]:
# Importing necessary libraries for building and evaluating the Random Forest model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Selecting the relevant features and target variable
# I'm using weather features and time of day to predict the daily subway entries
features = ['Is_Cold', 'Is_Rainy', 'Hour', 'Day_of_Week', 'tavg', 'prcp']  # These features represent weather and time
target = 'Daily Entries'  # The target I'm predicting is the number of daily entries in the subway system

# Splitting the data into training and testing sets
# I'm splitting the data with 80% for training and 20% for testing to evaluate how well the model generalizes
X = subway_final_data[features]
y = subway_final_data[target]

# Splitting into training (80%) and testing (20%) data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating the Random Forest Regressor model
# I chose 100 trees (n_estimators) and limited the tree depth to 10 to avoid overfitting
rf_model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)

# Training the Random Forest model on the training data
# The model will learn patterns in the training data using the selected features
rf_model.fit(X_train, y_train)

# Making predictions on the test data
# Now I’m using the model to predict the 'Daily Entries' for the testing dataset
rf_predictions = rf_model.predict(X_test)

# Evaluating the model's performance using Mean Squared Error (MSE)
# MSE will tell me how far the predicted values are from the actual values (lower is better)
rf_mse = mean_squared_error(y_test, rf_predictions)
print(f"Random Forest MSE: {rf_mse}")

# Optional: Print the first few predictions and compare with actual values
# This will give me a quick comparison between what the model predicted and the actual data
print(f"First 5 Predictions: {rf_predictions[:5]}")
print(f"Actual values: {y_test[:5].values}")

Version 2 code:

In [ ]:
# Step 1: Mount Google Drive to Access Data
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import Necessary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Step 3: Load GTFS and Supplemented Data Files
stops = pd.read_csv('/content/drive/My Drive/google_transit/stops.txt')
trips = pd.read_csv('/content/drive/My Drive/google_transit/trips.txt')
stop_times = pd.read_csv('/content/drive/My Drive/google_transit/stop_times.txt')
routes = pd.read_csv('/content/drive/My Drive/google_transit/routes.txt')

supplemented_stops = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/stops.txt')
supplemented_trips = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/trips.txt')
supplemented_stop_times = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/stop_times.txt')
supplemented_routes = pd.read_csv('/content/drive/My Drive/google_transit_supplemented/routes.txt')

# Step 4: Merge GTFS Data for Full Trip Information
gtfs_data = (
    stop_times
    .merge(stops, on='stop_id')
    .merge(trips, on='trip_id')
    .merge(routes, on='route_id')
)

# Merge with Supplemented Data if Necessary
gtfs_data = gtfs_data.merge(supplemented_stops, on='stop_id', how='left')
gtfs_data = gtfs_data.merge(supplemented_trips, on='trip_id', how='left')

print(gtfs_data.head())

In [ ]:
# Step 5: Load Turnstile Data
turnstile_data = pd.read_csv('/content/drive/MyDrive/MTA_Subway_Turnstile_Data_2022.csv')
turnstile_data.columns = turnstile_data.columns.str.strip()
turnstile_data.rename(columns={'Exits': 'EXITS', 'Entries': 'ENTRIES'}, inplace=True)

# Calculate Daily Entries and Exits
turnstile_data = turnstile_data.sort_values(by=['C/A', 'Unit', 'SCP', 'Date', 'Time'])
turnstile_data['Daily Entries'] = turnstile_data.groupby(['C/A', 'Unit', 'SCP'])['ENTRIES'].diff().fillna(0)
turnstile_data['Daily Exits'] = turnstile_data.groupby(['C/A', 'Unit', 'SCP'])['EXITS'].diff().fillna(0)

# Filter out negative values (counter resets)
turnstile_data = turnstile_data[(turnstile_data['Daily Entries'] >= 0) & (turnstile_data['Daily Exits'] >= 0)]

print(turnstile_data.head())

In [ ]:
#Loading Weather Data and Merge with Turnstile Data

#Ensuring weather data has correct datetime format for merging
weather_data['date'] = pd.to_datetime(weather_data['date'], format='%Y-%m-%d')
weather_data.head()

#Converting turnstile Date to datetime
turnstile_data['Date'] = pd.to_datetime(turnstile_data['Date'])

#Mapping the subway lines to 'mapped_line' before merging
line_map = {'NQR456W': '456', 'NQR': 'NQR', 'ACE': 'ACE', 'BDFM': 'BDFM', '123': '123', '7': '7'}
turnstile_data['mapped_line'] = turnstile_data['Line Name'].map(line_map)

#Merging Turnstile Data with Weather Data, ensuring 'mapped_line' is retained
subway_weather_data = pd.merge(turnstile_data, weather_data, left_on='Date', right_on='date', how='left')

#Extracting relevant weather features (e.g., temperature, precipitation)
subway_weather_data['Is_Cold'] = subway_weather_data['tavg'].apply(lambda x: 1 if x < 32 else 0)
subway_weather_data['Is_Rainy'] = subway_weather_data['prcp'].apply(lambda x: 1 if x > 0 else 0)
subway_weather_data.head()

In [ ]:
# Step 8: Extract Time Features for Modeling
subway_weather_data['Hour'] = pd.to_datetime(subway_weather_data['Time']).dt.hour
subway_weather_data['Day_of_Week'] = pd.to_datetime(subway_weather_data['Date']).dt.dayofweek

# Step 9: Define Features and Target
features = ['Is_Cold', 'Is_Rainy', 'tavg', 'prcp', 'Hour', 'Day_of_Week']
target = 'Daily Entries'

X = subway_weather_data[features]
y = subway_weather_data[target]

In [ ]:

# Step 10: Split Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training features: {X_train.shape}, Training target: {y_train.shape}")
print(f"Testing features: {X_test.shape}, Testing target: {y_test.shape}")

In [ ]:
# Step 11: Train Random Forest Model
rf_model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

In [ ]:
# Step 12: Make Predictions and Evaluate Model
y_pred = rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print("First 5 Predictions:", y_pred[:5])
print("Actual Values:", y_test[:5].values)

# Step 13: Plot Feature Importances
importances = rf_model.feature_importances_
indices = range(len(importances))

plt.figure(figsize=(10, 6))
plt.title("Feature Importances")
plt.barh(indices, importances, align="center")
plt.yticks(indices, features)
plt.xlabel("Relative Importance")
plt.show()

In [ ]:
# Import necessary libraries for additional improvements
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

# Log-transform the target variable to reduce the impact of large values
subway_weather_data['Log_Daily_Entries'] = np.log1p(subway_weather_data['Daily Entries'])

# Step 1: Define Features and Transformed Target
features = ['Is_Cold', 'Is_Rainy', 'tavg', 'prcp', 'Hour', 'Day_of_Week']
target = 'Log_Daily_Entries'

X = subway_weather_data[features]
y = subway_weather_data[target]

# Step 2: Feature Scaling to Normalize Feature Values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Split the Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(f"Training features: {X_train.shape}, Training target: {y_train.shape}")
print(f"Testing features: {X_test.shape}, Testing target: {y_test.shape}")

In [ ]:
# Step 4: Set up Random Forest with Hyperparameter Tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 20],
    'min_samples_split': [2, 5, 10]
}

rf = RandomForestRegressor(random_state=42)
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, n_jobs=-1, scoring='neg_mean_squared_error')

# Train the Random Forest Model with Grid Search
grid_search.fit(X_train, y_train)

# Display the Best Parameters from Grid Search
print("Best Parameters:", grid_search.best_params_)